name: CI Workflow with ESLint and Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: List top-level files in the repository (Debug)
      - name: List top-level files
        run: ls -l

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install
        working-directory: ./project_template/project

      # Step 4: List all files in the project_template directory (Debug)
      - name: List files in project_template directory
        run: ls -R ./project_template

      # Step 5: Check for ESLint config file existence
      - name: Check if ESLint config exists
        run: ls -l ./project_template/project/eslint.config.js
        working-directory: ./project_template/project

      # Step 6: Run ESLint with config file
      - name: Run ESLint with config file
        run: npx eslint . --config ./project_template/project/eslint.config.js
        working-directory: ./project_template/project





