name: CI Workflow with ESLint and Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      # checkout code
      - name: Checkout code
        uses: actions/checkout@v2

      # list files in project_template 
      - name: List files in project_template directory
        run: ls -R ./project_template

      # list files in project_template/project directory
      - name: List files in project_template/project directory
        run: ls -l ./project_template/project

      # Install dependencies
      - name: Install dependencies
        run: npm install
        working-directory: ./project_template/project

      # eslint with config file and auto-fix
      - name: Run ESLint with auto-fix
        run: npx eslint . --config $GITHUB_WORKSPACE/project_template/project/eslint.config.js --fix
        working-directory: ./project_template/project

  test:
    runs-on: ubuntu-latest
    needs: lint  # linting completes before running tests

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # set up node.js
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      # dependencies in the correct directory
      - name: Install dependencies
        run: npm install
        working-directory: ./project_template/project

      # run Tests with coverage
      - name: Run Tests with Coverage
        run: npm run test:coverage
        working-directory: ./project_template/project

      # upload coverage to github actions
      - name: Upload Coverage Report to GitHub Actions (Text)
        if: success()  # only upload if success
        run: |
          echo "Code coverage report:"
          cat ./coverage/coverage-summary.txt  # Show coverage summary in log

      # upload report as artifact
      - name: Upload HTML Coverage Report as Artifact
        if: success()
        uses: actions/upload-artifact@v4  # Updated to v4
        with:
          name: coverage-report
          path: ./coverage/lcov-report  # coverage report as artifact


