name: CI Workflow with ESLint and Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: List files in project_template directory to confirm structure
      - name: List files in project_template directory
        run: ls -R ./project_template

      # Step 3: List files in project_template/project directory
      - name: List files in project_template/project directory
        run: ls -l ./project_template/project

      # Step 4: Install dependencies
      - name: Install dependencies
        run: npm install
        working-directory: ./project_template/project

      # Step 5: Run ESLint with config file using absolute path (without working-directory)
      - name: Run ESLint with config file
        run: npx eslint . --config $GITHUB_WORKSPACE/project_template/project/eslint.config.js
