name: Continuous Integration (CI)

on:
  push:
    branches:
      - master  #  when changes are pushed to the m branch
  pull_request:
    branches:
      - master #  on pull requests to the m branch

jobs:
  lint:
    runs-on: ubuntu-latest  # latest Ubuntu for the runner
    steps:
      #  checkout code from repo
      - name: Checkout code
        uses: actions/checkout@v2

      # node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  #  node.js to match project

      #install dependencies
      - name: Install dependencies
        working-directory: ./project_template/project  # change to wher package.json is
        run: npm install  # Install npm dependencies

      # 4. Run ESLint
      - name: Run ESLint
        working-directory: ./project_template/project  # Same here
        run: npm run lint  # Run the lint script
