name: CD (Continious Delievery)

on:
  push:
    branches:
      - master  

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install Dependencies
        run: npm install
        working-directory: ./project_template/project  

      - name: Run ESLint
        run: npx eslint . --fix
        working-directory: ./project_template/project  

      - name: Build Project
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
